logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: error

spring:
  sql:
    init:
      data-locations: classpath:/db/h2_data/data.sql
      schema-locations: classpath:/db/h2_data/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-stg
  datasource:
    url: jdbc:h2:mem:app_db
    driver-class-name: org.h2.Driver
    username: sa
    password: saStg

  flyway:
    enabled: true
    locations: classpath:db/migration
    user: sa
    password: saStg
    url: jdbc:h2:mem:app_db
    schemas: app_db